import { lazy } from "react";

/** Cargadores de cada página: App.tsx los usa con lazy() y navConfig para precargar. */
export const loaders = {
  LandingPage: () => import("../pages/LandingPage"),
  ClubsLandingPage: () => import("../pages/ClubsLandingPage"),
  Login: () => import("../pages/Login"),
  Register: () => import("../pages/Register"),
  NotFound: () => import("../pages/NotFound"),
  Demo: () => import("../pages/Demo"),
  DemoEntry: () => import("../pages/DemoEntry"),
  Dashboard: () => import("../pages/Dashboard"),
  Profile: () => import("../pages/Profile"),
  Calendar: () => import("../pages/Calendar"),
  Training: () => import("../pages/Training"),
  TrainingSession: () => import("../pages/TrainingSession"),
  DiagnosticTest: () => import("../pages/DiagnosticTest"),
  Chat: () => import("../pages/Chat"),
  Leaderboard: () => import("../pages/Leaderboard"),
  Achievements: () => import("../pages/Achievements"),
  Onboarding: () => import("../pages/Onboarding"),
  Settings: () => import("../pages/Settings"),
  OnboardingResult: () => import("../pages/OnboardingResult"),
  ParentDashboard: () => import("../pages/parent/ParentDashboard"),
  ParentChild: () => import("../pages/parent/ParentChild"),
  ParentMedical: () => import("../pages/parent/ParentMedical"),
  ClubDashboard: () => import("../pages/club/ClubDashboard"),
  Members: () => import("../pages/club/Members"),
  Teams: () => import("../pages/club/Teams"),
  Fees: () => import("../pages/club/Fees"),
  Medical: () => import("../pages/club/Medical"),
  Attendance: () => import("../pages/club/Attendance"),
  Fixtures: () => import("../pages/club/Fixtures"),
  ClubSetup: () => import("../pages/club/ClubSetup"),
  ParentFees: () => import("../pages/parent/ParentFees"),
  ParentAnnouncements: () => import("../pages/parent/ParentAnnouncements"),
  TrainingLoad: () => import("../pages/club/TrainingLoad"),
  Reports: () => import("../pages/club/Reports"),
  Communication: () => import("../pages/club/Communication"),
  Classroom: () => import("../pages/Classroom"),
  ClassroomModule: () => import("../pages/ClassroomModule"),
  ClassroomLesson: () => import("../pages/ClassroomLesson"),
  AdminDashboard: () => import("../pages/admin/AdminDashboard"),
  Users: () => import("../pages/admin/Users"),
  Analytics: () => import("../pages/admin/Analytics"),
  AdminSettings: () => import("../pages/admin/Settings"),
  AdminCourses: () => import("../pages/admin/Courses"),
} as const;

export type PageName = keyof typeof loaders;

export const LandingPage = lazy(loaders.LandingPage);
export const ClubsLandingPage = lazy(loaders.ClubsLandingPage);
export const Login = lazy(loaders.Login);
export const Register = lazy(loaders.Register);
export const NotFound = lazy(loaders.NotFound);
export const Demo = lazy(loaders.Demo);
export const DemoEntry = lazy(loaders.DemoEntry);
export const Dashboard = lazy(loaders.Dashboard);
export const Profile = lazy(loaders.Profile);
export const Calendar = lazy(loaders.Calendar);
export const Training = lazy(loaders.Training);
export const TrainingSession = lazy(loaders.TrainingSession);
export const DiagnosticTest = lazy(loaders.DiagnosticTest);
export const Chat = lazy(loaders.Chat);
export const Leaderboard = lazy(loaders.Leaderboard);
export const Achievements = lazy(loaders.Achievements);
export const Onboarding = lazy(loaders.Onboarding);
export const Settings = lazy(loaders.Settings);
export const OnboardingResult = lazy(loaders.OnboardingResult);
export const ParentDashboard = lazy(loaders.ParentDashboard);
export const ParentChild = lazy(loaders.ParentChild);
export const ParentMedical = lazy(loaders.ParentMedical);
export const ClubDashboard = lazy(loaders.ClubDashboard);
export const Members = lazy(loaders.Members);
export const Teams = lazy(loaders.Teams);
export const Fees = lazy(loaders.Fees);
export const Medical = lazy(loaders.Medical);
export const Attendance = lazy(loaders.Attendance);
export const Fixtures = lazy(loaders.Fixtures);
export const ClubSetup = lazy(loaders.ClubSetup);
export const ParentFees = lazy(loaders.ParentFees);
export const ParentAnnouncements = lazy(loaders.ParentAnnouncements);
export const TrainingLoad = lazy(loaders.TrainingLoad);
export const Reports = lazy(loaders.Reports);
export const Communication = lazy(loaders.Communication);
export const Classroom = lazy(loaders.Classroom);
export const ClassroomModule = lazy(loaders.ClassroomModule);
export const ClassroomLesson = lazy(loaders.ClassroomLesson);
export const AdminDashboard = lazy(loaders.AdminDashboard);
export const Users = lazy(loaders.Users);
export const Analytics = lazy(loaders.Analytics);
export const AdminSettings = lazy(loaders.AdminSettings);
export const AdminCourses = lazy(loaders.AdminCourses);
